version: '3.7'

services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/${PROFILE}/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
    ports:
      - "3306:3306"
    env_file:
      - db.env
    networks:
      - traefik_web  
  
  nextcloud:
    image: ${NC_IMAGE}
#    ports:
#      - 80:80
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/${PROFILE}/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - OVERWRITEPROTOCOL=https
#      - OVERWRITEWEBROOT=/nextcloud-dev
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    env_file:
      - db.env
    depends_on:
      - db
    networks:
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure-${PROFILE}"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=leresolver"


  # traefik:
  #   image: "traefik:v2.3"
  #   restart: unless-stopped
  #   container_name: "traefik"
  #   command:
  #     #- "--log.level=DEBUG"
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.websecure-dev.address=:444"
  #     - "--entrypoints.websecure-test.address=:446"
  #     - "--providers.file.directory=/var/config"
  #     - "--providers.file.watch=true"
  #     - "--accesslog=true"
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #     - "444:444"
  #     - "446:446"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  traefik_web:
    external: true
  
