version: '3.7'

services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/${PROFILE}/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
    ports:
      - "3306:3306"
    env_file:
      - db.env
  
  nextcloud:
    build:
      context: nc/
      args:
        NC_IMAGE: ${NC_IMAGE}
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/${PROFILE}/nextcloud:/var/www/html
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - MYSQL_HOST=db
#      - OVERWRITEPROTOCOL=https
#      - OVERWRITEWEBROOT=/nextcloud-dev
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    env_file:
      - db.env
    depends_on:
      - db


