version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/${PROFILE}/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
    # ports:
    #   - "3406:3306"
    env_file:
      - db.env

  nextcloud:
    image: "nextcloud:20.0.3-apache"
#    ports:
#      - 8081:80
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/${PROFILE}/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - OVERWRITEPROTOCOL=https
#      - OVERWRITEWEBROOT=/nextcloud-dev
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    env_file:
      - db.env
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls"


#   app:
#     image: ${NC_IMAGE}
#     restart: unless-stopped
#     volumes:
#       - ${DATA_DIR}/${PROFILE}/nextcloud:/var/www/html
#     environment:
#       - MYSQL_HOST=db
# #      - OVERWRITEPROTOCOL=https
#       - OVERWRITEWEBROOT=/nextcloud-dev
#     env_file:
#       - db.env
#     depends_on:
#       - db

  traefik:
    image: "traefik:v2.3"
    restart: unless-stopped
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:${HTTPS_PORT}"
      - "--providers.file.directory=/var/config"
      - "--providers.file.watch=true"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "8080:8080"
      - ${HTTPS_PORT}:${HTTPS_PORT}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    
#   web:
#     build: ./web
#     restart: unless-stopped
#     volumes:
#       - ${DATA_DIR}/${PROFILE}/nextcloud:/var/www/html:ro
#     # ports:
#     #   - 80:80
#     depends_on:
#       - app
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.nextcloud.rule=Host(`localhost`) && Path(`/nextcloud-dev`)"
#       - "traefik.http.routers.nextcloud.rule=Host(`localhost`)"
#       - "traefik.http.routers.nextcloud.entrypoints=websecure"
#       - "traefik.http.routers.nextcloud.tls"
# #      - "traefik.http.routers.nextcloud-secure.entrypoints=websecure"
# #      - "traefik.http.routers.nextcloud-secure.tls"

# networks:
#   default:
#     external:
#       name: traefik-deploy_default