ARG NC_IMAGE

FROM ${NC_IMAGE}

# RUN apt-get update; apt-get install -y \
#      cron

# COPY crontab-extends* /
# WORKDIR /
# RUN chmod 755 crontab-extends.sh

# CMD ["/bin/bash", "-c", "/crontab-extends.sh; apache2-foreground"]